### ISSUE TITLE
import npm:preact not working on jsr.io

### ISSUE THREAD

**Issue by avalero** [jsr-io/jsr#373]
Problem detected when publishing: https://jsr.io/@avalero/preact-hooks

I have created a custom hook for preact - https://github.com/avalero/preact-hooks
The package tries to import `preact` whith npm, as shown in this `deno.json`

```json
{
  "name": "@avalero/preact-hooks",
  "version": "0.0.4",
  "exports": {
    ".": "./mod.ts",
    "./useFetch": "./fetch/useFetch.ts",
    "./Fetch": "./fetch/mod.ts"
  },
  "description": "Preact hooks",
  "publish": {
    "exclude": [".gitignore", ".vscode", ".github"]
  },
  "imports": {
    "preact": "npm:preact@10.19.6",
    "@preact/signals": "npm:preact/signals@1.2.2",
    "@preact/signals-core": "npm:/*@preact/signals-core@1.5.1"
  }
}
```
Custom hook is as follows and works well when importing preact with esm and using it on Deno Fresh:
```typescript
import { useState } from "preact/hooks";

/**
 * Fetch methods
 */
export type FetchMethods = "GET" | "POST" | "PUT" | "DELETE";

/**
 * Fetch options
 * @param method fetch method
 * @param headers fetch headers
 * @param body fetch body
 * @example { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ key: "value" }) }
 * @example { method: "GET", headers: { "Content-Type": "application/json" }, body: "" }
 */
export type FetchOptions = {
  method: FetchMethods;
  headers: Record<string, string>;
  body: string;
};

/**
 * Hook for fetching data from a URL
 * @param url url to fetch data from
 * @param options fetch options: method, headers, body
 * @returns {data, loading, error, refetch} data is the fetched data, loading is a boolean indicating if the fetch is in progress, error is the error if the fetch failed, refetch is a function to refetch the data
 * @example const { data, loading, error, refetch } = useFetch<DataType>("https://api.example.com/data");
 * @example const { data, loading, error } = useFetch<DataType>("https://api.example.com/data", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ key: "value" }) });
 */
export function useFetch<Type>(
  url: string,
  options?: FetchOptions,
): {
  data: Type | null;
  loading: boolean;
  error: Error | null;
  refetch: () => void;
} {
  const [data, setData] = useState<Type | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<Error | null>(null);

  fetch(url, options)
    .then((response) => {
      if (!response.ok) {
        throw new Error("Failed to fetch data");
      }
      return response.json();
    })
    .then((data) => setData(data))
    .catch((error) => setError(error))
    .finally(() => setLoading(false));

  const refetch = () => {
    setLoading(true);
    fetch(url, options)
      .then((response) => {
        if (!response.ok) {
          throw new Error("Failed to fetch data");
        }
        return response.json();
      })
      .then((data) => setData(data))
      .catch((error) => setError(error))
      .finally(() => setLoading(false));
  };

  return { data, loading, error, refetch };
}
```

But when importing `preact` using `npm` (as required by jsr.io) it does not work, providing the following error
```
Cannot read properties of undefined (reading '__H')
> 1 | import{options as n}from"preact";var t,r,u,i,o=0,f=[],c=[],e=n,a=e.__b,v=e.__r,l=e.diffed,m=e.__c,s=e.unmount,d=e.__;function h(n,t){e.__h&&e.__h(r,n,o||t),o=0;var u=r.__H||(r.__H={__:[],__h:[]});return n>=u.__.length&&u.__.push({__V:c}),u.__[n]}function p(n){return o=1,y(D,n)}function y(n,u,i){var o=h(t++,2);if(o.t=n,!o.__c&&(o.__=[i?i(u):D(void 0,u),function(n){var t=o.__N?o.__N[0]:o.__[0],r=o.t(t,n);t!==r&&(o.__N=[r,o.__[1]],o.__c.setState({}))}],o.__c=r,!r.u)){var f=function(n,t,r){if(!o.__c.__H)return!0;var u=o.__c.__H.__.filter(function(n){return!!n.__c});if(u.every(function(n){return!n.__N}))return!c||c.call(this,n,t,r);var i=!1;return u.forEach(function(n){if(n.__N){var t=n.__[0];n.__=n.__N,n.__N=void 0,t!==n.__[0]&&(i=!0)}}),!(!i&&o.__c.props===n)&&(!c||c.call(this,n,t,r))};r.u=!0;var c=r.shouldComponentUpdate,e=r.componentWillUpdate;r.componentWillUpdate=function(n,t,r){if(this.__e){var u=c;c=void 0,f(n,t,r),c=u}e&&e.call(this,n,t,r)},r.shouldComponentUpdate=f}return o.__N||o.__}function _(n,u){var i=h(t++,3);!e.__s&&C(i.__H,u)&&(i.__=n,i.i=u,r.__H.__h.push(i))}function A(n,u){var i=h(t++,4);!e.__s&&C(i.__H,u)&&(i.__=n,i.i=u,r.__h.push(i))}function F(n){return o=5,q(function(){return{current:n}},[])}function T(n,t,r){o=6,A(function(){return"function"==typeof n?(n(t()),function(){return n(null)}):n?(n.current=t(),function(){return n.current=null}):void 0},null==r?r:r.concat(n))}function q(n,r){var u=h(t++,7);return C(u.__H,r)?(u.__V=n(),u.i=r,u.__h=n,u.__V):u.__}function x(n,t){return o=8,q(function(){return n},t)}function P(n){var u=r.context[n.__c],i=h(t++,9);return i.c=n,u?(null==i.__&&(i.__=!0,u.sub(r)),u.props.value):n.__}function V(n,t){e.useDebugValue&&e.useDebugValue(t?t(n):n)}function b(n){var u=h(t++,10),i=p();return u.__=n,r.componentDidCatch||(r.componentDidCatch=function(n,t){u.__&&u.__(n,t),i[1](n)}),[i[0],function(){i[1](void 0)}]}function g(){var n=h(t++,11);if(!n.__){for(var u=r.__v;null!==u&&!u.__m&&null!==u.__;)u=u.__;var i=u.__m||(u.__m=[0,0]);n.__="P"+i[0]+"-"+i[1]++}return n.__}function j(){for(var n;n=f.shift();)if(n.__P&&n.__H)try{n.__H.__h.forEach(z),n.__H.__h.forEach(B),n.__H.__h=[]}catch(t){n.__H.__h=[],e.__e(t,n.__v)}}e.__b=function(n){r=null,a&&a(n)},e.__=function(n,t){n&&t.__k&&t.__k.__m&&(n.__m=t.__k.__m),d&&d(n,t)},e.__r=function(n){v&&v(n),t=0;var i=(r=n.__c).__H;i&&(u===r?(i.__h=[],r.__h=[],i.__.forEach(function(n){n.__N&&(n.__=n.__N),n.__V=c,n.__N=n.i=void 0})):(i.__h.forEach(z),i.__h.forEach(B),i.__h=[],t=0)),u=r},e.diffed=function(n){l&&l(n);var t=n.__c;t&&t.__H&&(t.__H.__h.length&&(1!==f.push(t)&&i===e.requestAnimationFrame||((i=e.requestAnimationFrame)||w)(j)),t.__H.__.forEach(function(n){n.i&&(n.__H=n.i),n.__V!==c&&(n.__=n.__V),n.i=void 0,n.__V=c})),u=r=null},e.__c=function(n,t){t.some(function(n){try{n.__h.forEach(z),n.__h=n.__h.filter(function(n){return!n.__||B(n)})}catch(r){t.some(function(n){n.__h&&(n.__h=[])}),t=[],e.__e(r,n.__v)}}),m&&m(n,t)},e.unmount=function(n){s&&s(n);var t,r=n.__c;r&&r.__H&&(r.__H.__.forEach(function(n){try{z(n)}catch(n){t=n}}),r.__H=void 0,t&&e.__e(t,r.__v))};var k="function"==typeof requestAnimationFrame;function w(n){var t,r=function(){clearTimeout(u),k&&cancelAnimationFrame(t),setTimeout(n)},u=setTimeout(r,100);k&&(t=requestAnimationFrame(r))}function z(n){var t=r,u=n.__c;"function"==typeof u&&(n.__c=void 0,u()),r=t}function B(n){var t=r;n.__c=n.__(),r=t}function C(n,t){return!n||n.length!==t.length||t.some(function(t,r){return t!==n[r]})}function D(n,t){return"function"==typeof t?t(n):t}export{x as useCallback,P as useContext,V as useDebugValue,_ as useEffect,b as useErrorBoundary,g as useId,T as useImperativeHandle,A as useLayoutEffect,q as useMemo,y as useReducer,F as useRef,p as useState};
    |                                                                                                                                                                         ^
  2 | //# sourceMappingURL=hooks.module.js.map
  3 |
TypeError: Cannot read properties of undefined (reading '__H')
    at h (file:///home/avalero/.cache/deno/npm/registry.npmjs.org/preact/10.19.6/hooks/dist/hooks.mjs:1:169)
    at y (file:///home/avalero/.cache/deno/npm/registry.npmjs.org/preact/10.19.6/hooks/dist/hooks.mjs:1:303)
    at p (file:///home/avalero/.cache/deno/npm/registry.npmjs.org/preact/10.19.6/hooks/dist/hooks.mjs:1:272)
    at useFetch (https://jsr.io/@avalero/preact-hooks/0.0.4/fetch/useFetch.ts:39:27)
    at Object.Characters (file:///home/avalero/jsr/test-hooks/islands/Characters.tsx:4:36)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3237)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2543)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
 ```

**Comment by avalero** [comment]
Fixed updating `deno.json` to
```json
{
  "name": "@avalero/preact-hooks",
  "version": "0.0.5",
  "exports": {
    ".": "./mod.ts",
    "./useFetch": "./fetch/useFetch.ts",
    "./Fetch": "./fetch/mod.ts"
  },
  "description": "Preact hooks",
  "publish": {
    "exclude": [".gitignore", ".vscode", ".github"]
  },
  "imports": {
    "preact": "npm:preact@10.19.6"
  },
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  }
}
```

**Comment by lucacasonato** [comment]
Are you using this package from a Fresh project?

**Comment by lucacasonato** [comment]
I did not get a further response. I will close the issue because it is stale.
